In [1]:
# 🌟 Exercise 1 : Array Creation And Manipulation
# Create a 1D NumPy array containing numbers from 0 to 9
import numpy as np

arr1 = np.arange(10)
print("Exercise 1 Output:\n", arr1)


# 🌟 Exercise 2 : Type Conversion And Array Operations
# Convert a list into a NumPy array and change data type to integer
lst = [3.14, 2.17, 0, 1, 2]
arr2 = np.array(lst, dtype=int)
print("\nExercise 2 Output:\n", arr2)


# 🌟 Exercise 3 : Working With Multi-Dimensional Arrays
# Create a 3x3 NumPy array with values from 1 to 9
arr3 = np.arange(1, 10).reshape(3, 3)
print("\nExercise 3 Output:\n", arr3)


# 🌟 Exercise 4 : Creating Multi-Dimensional Array With Random Numbers
# Create a 2D NumPy array of shape (4, 5) filled with random numbers
arr4 = np.random.rand(4, 5)
print("\nExercise 4 Output:\n", arr4)


# 🌟 Exercise 5 : Indexing Arrays
# Select the second row from a given 2D NumPy array
array5 = np.array([[21,22,23,22,22],
                   [20,21,22,23,24],
                   [21,22,23,22,22]])
second_row = array5[1]
print("\nExercise 5 Output:\n", second_row)


# 🌟 Exercise 6 : Reversing Elements
# Reverse the order of elements in a given 1D NumPy array
arr6 = np.arange(10)
reversed_arr = arr6[::-1]
print("\nExercise 6 Output:\n", reversed_arr)


# 🌟 Exercise 7 : Identity Matrix
# Create a 4x4 identity matrix
arr7 = np.eye(4)
print("\nExercise 7 Output:\n", arr7)


# 🌟 Exercise 8 : Simple Aggregate Funcs
# Find the sum and average of a given 1D array
arr8 = np.arange(10)
total = np.sum(arr8)
average = np.mean(arr8)
print("\nExercise 8 Output:\nSum:", total, "Average:", average)


# 🌟 Exercise 9 : Create Array And Change Its Structure
# Create a NumPy array with elements 1 to 20 and reshape it into 4x5
arr9 = np.arange(1, 21).reshape(4, 5)
print("\nExercise 9 Output:\n", arr9)


# 🌟 Exercise 10 : Conditional Selection Of Values
# Extract all odd numbers from a given NumPy array
arr10 = np.arange(10)
odds = arr10[arr10 % 2 == 1]
print("\nExercise 10 Output:\n", odds)


Exercise 1 Output:
 [0 1 2 3 4 5 6 7 8 9]

Exercise 2 Output:
 [3 2 0 1 2]

Exercise 3 Output:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Exercise 4 Output:
 [[0.12828113 0.18078814 0.50939989 0.54715663 0.8019598 ]
 [0.65123705 0.08396077 0.9512796  0.14652696 0.47595648]
 [0.22588298 0.78101996 0.04107727 0.08088428 0.5007805 ]
 [0.92891592 0.0830385  0.81824198 0.57509487 0.80821019]]

Exercise 5 Output:
 [20 21 22 23 24]

Exercise 6 Output:
 [9 8 7 6 5 4 3 2 1 0]

Exercise 7 Output:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Exercise 8 Output:
Sum: 45 Average: 4.5

Exercise 9 Output:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Exercise 10 Output:
 [1 3 5 7 9]
